# Generated by Django 3.2.25 on 2025-02-03 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=122)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
