# Generated by Django 3.2.25 on 2025-02-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='tb_contact',
        ),
    ]
