# Generated by Django 3.2.25 on 2025-02-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20250204_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
