# Generated by Django 3.2.25 on 2025-02-04 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20250204_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='tb_user',
        ),
    ]
